global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
  - job_name: 'local'
    static_configs:
      - targets: ['host.docker.internal:8000']
